### ISSUE TITLE
Bug: `global_length` for `PRange`

### ISSUE THREAD

**Issue by JordiManyer** [fverdugo/PartitionedArrays.jl#113]
I believe there is a typo/mistake [here](https://github.com/fverdugo/PartitionedArrays.jl/blob/fc741f2cea6785c2fee28e364f81ceb30b871e45/src/p_range.jl#L1645C60-L1645C60). 

I think it should be

```julia
global_length(pr::PRange) = map(global_length,partition(pr))
```

**Comment by amartinhuertas** [comment]
Yes, it seems so. Can you please fix it? I will accept the PR.

**Comment by amartinhuertas** [comment]
Also can you add a test on this function?
