### ISSUE TITLE
Bug: `copy` returns matrix with wrong communication pattern

### ISSUE THREAD

**Issue by JordiManyer** [fverdugo/PartitionedArrays.jl#140]
Hi @fverdugo, 

There is an issue with the current `copy` function. I detected it for the old implemetation of `PSparseMatrix`, but I believe it should affect the new one as well. 

Here is a MWE: 

```julia
using PartitionedArrays

np = 2
ranks = with_debug() do distribute
  distribute(LinearIndices((np,)))
end

n = 4
rows = uniform_partition(ranks,n)
I,J,V = map(ranks) do r
    if r == 1
        I = [1,2,3]
        J = [1,2,3]
    elseif r == 2
        I = [3,4]
        J = [3,4]
    end
    I,J,fill(Float64(r),length(J))
end |> tuple_of_arrays
A = old_psparse!(I,J,V,rows,rows) |> fetch

B = copy(A)

A_caches = A.cache.items[1].cache
B_caches = B.cache.items[1].cache
```

which yields: 

```
PartitionedArrays.VectorAssemblyCache{Float64}(Int32[2], Int32[], JaggedArray{Int32,Int32}(Vector{Int32}[[3]]), JaggedArray{Int32,Int32}(Vector{Int32}[]), JaggedArray{Float64,Int32}([[0.0]]), JaggedArray{Float64,Int32}(Vector{Float64}[]))

PartitionedArrays.VectorAssemblyCache{Float64}(Int32[2], Int32[], JaggedArray{Int32,Int32}(Vector{Int32}[[]]), JaggedArray{Int32,Int32}(Vector{Int32}[]), JaggedArray{Float64,Int32}([Float64[]]), JaggedArray{Float64,Int32}(Vector{Float64}[]))
```

The issue here is the following: We are not implementing `copy`, but rather `copyto!` and `similar`. Additionally, `similar` depends on the type of the local matrices, in our case `SparseArrays`. 
I believe the issue is that `SparseArrays`'s `similar` returns a sparse matrix **without non-zero elements**. This makes the construction of the assembly caches to be wrong. 

A possible solution (without changing the behaviour of `SparseArrays` is to also implement `copy` in the following way: 

```julia
function Base.copy(a::PSparseMatrix)
  mats = map(copy,partition(a))
  cache = map(copy_cache,a.cache)
  return PSparseMatrix(mats,partition(axes(a,1)),partition(axes(a,2)),cache)
end
```

where copying the cache is not necessary, but is more efficient (I believe).

**Comment by fverdugo** [comment]
Hi @JordiManyer, it makes sense. Thanks for reporting! 

Feel free to add the fix + some test + PR.
