### ISSUE TITLE
ERROR: MethodError: no method matching psparse(::Vector{…}, ::Vector{…}, ::Vector{…}, ::Vector{…}, ::Vector{…})

### ISSUE THREAD

**Issue by ZhangFengshun** [fverdugo/PartitionedArrays.jl#145]
using PartitionedArrays
using IterativeSolvers
using LinearAlgebra

np = 3
n = 5

ranks = LinearIndices((np,))
map(ranks) do rank
    println("Hello, world! I am proc $rank of $np.")
end;

row_partition = uniform_partition(ranks, n)
IV = map(row_partition) do row_indices
    I,V = Int[], Float64[]
    for global_row in local_to_global(row_indices)
        if global_row == 1
            v = 1.0
        elseif global_row == n
            v = -1.0
        else
            continue
        end
        push!(I,global_row)
        push!(V,v)
    end
    I,V
end

II,VV = tuple_of_arrays(IV);

b = PVector(II, VV, row_partition) |> fetch;

IJV = map(row_partition) do row_indices
    I,J,V = Int[], Int[], Float64[]
    for global_row in local_to_global(row_indices)
        if global_row in (1,n)
            push!(I,global_row)
            push!(J,global_row)
            push!(V,1.0)
        else
            push!(I,global_row)
            push!(J,global_row-1)
            push!(V,-1.0)
            push!(I,global_row)
            push!(J,global_row)
            push!(V,2.0)
            push!(I,global_row)
            push!(J,global_row+1)
            push!(V,-1.0)
        end
    end
    I,J,V
end
I,J,V = tuple_of_arrays(IJV);
col_partition = row_partition;
A = psparse(I,J,V,row_partition,col_partition);

x = similar(b,axes(A,2))
x .= b
IterativeSolvers.cg!(x,A,b)
r = A*x - b
norm(r)

I run above code, which is an example of "[Distributed sparse linear solve](https://www.francescverdugo.com/PartitionedArrays.jl/stable/examples/#Distributed-sparse-linear-solve)", but got errors below.
![image](https://github.com/fverdugo/PartitionedArrays.jl/assets/89072581/81110003-79b6-4b8b-9a31-7d25aaf67c9f)

**Comment by fverdugo** [comment]
Hi @ZhangFengshun make sure that you are using PartitionedArrays v0.4 or higher.

**Comment by ZhangFengshun** [comment]
> Hi @ZhangFengshun make sure that you are using PartitionedArrays v0.4 or higher.

Thanks, it works!
