### ISSUE TITLE
Implement matrix-matrix and matrix-matrix-matrix product

### ISSUE THREAD

**Issue by fverdugo** [fverdugo/PartitionedArrays.jl#15]
This would be needed for multigrid preconditioners.

**Comment by stevengj** [comment]
Wouldn't you generally want to leave such products implicit, ala https://github.com/JuliaSmoothOptimizers/LinearOperators.jl, i.e. `A * B` returns an operator that computes `(A * B) * x` via `A * (B * x)`?

**Comment by carlodev** [comment]
I would try to implement this feature. I was looking at the PSparseMatrix and PVector product. Do you have any suggestions on where I can start from? or reference to better understand how the code/package internally works (I get lost in the indexing notation)?

**Comment by fverdugo** [comment]
Hi Carlos, I am refactoring the code with the main objective of improving the documentation so that others can contribute easier. 

See the work going on in branch https://github.com/fverdugo/PartitionedArrays.jl/tree/remove_abstractpdata

(the name is a bit confusing, sorry...)

If you are not in a hurry, it would better to wait.

In the meanwhile, you can build and read the documentation in the branch and start providing feedback for the parts that are relatively mature (parallel primitives and partitioned ranges).

**Comment by stevengj** [comment]
@fverdugo, can you link the commit where this was completed?

**Comment by fverdugo** [comment]
Yes, I should have mentioned this, while closing the issue.

It was in PR #134 as part of the implementation of smoothed aggregation AMG solvers.
