### ISSUE TITLE
GSoC 2024 Task #1: Extend Notebook to PartitionedArrays.jl Tutorial

### ISSUE THREAD

**Issue by GeliezaK** [fverdugo/PartitionedArrays.jl#151]
cc @fverdugo @amartinhuertas @oriolcg 

In the meeting on 2024-05-27, the following steps were discussed to get started with the GSoC project: 
- [x] Familiarize with PartitionedArrays.jl package by working with Jacobi tutorial notebook
- [x] add explanatory text and instructions to the notebook to create a tutorial
- [x] create first issue and post link to it on social media platform

**Comment by GeliezaK** [comment]
Meeting notes from 2024-05-30: 

- Resources to learn working with PartitionedArrays: 
1. Notebook Sparse Vector-Matrix Product from Francesc
2. Jacobi tutorial 
3. parallel distributed poisson tutorial: https://gridap.github.io/GridapWorkshopNCI2023/tutorials/T5_poisson_distributed/ 

- How to run documentation locally: https://github.com/gridap/Gridap.jl/wiki/How-to-build-the-documentation-locally 
- embed images for documentation via assets folder
- Final pull request previous GSoC: https://github.com/gridap/GridapMakie.jl/pull/24  
- Coding style guidelines: https://docs.julialang.org/en/v1/manual/style-guide/ 
- Thesis AMG algorithms: [Tobias Wiesner.pdf](https://github.com/fverdugo/PartitionedArrays.jl/files/15497166/Tobias.Wiesner.pdf)
 

Action points: 
- [ ] create gsoc branch and label 
- [ ] read PartitionedArrays documentation
- [ ] add images from lecture & more explanations to Jacobi notebook
- [ ] add Jacobi notebook to documentation
- [ ] work with parallel distributed Poisson tutorial 
- [ ] work with sparse matrix vector product notebook
- [ ] make an own toy project to get familiar with PartitionedArrays methods and types 
- [ ] start reading literature to get an understanding of aggregation algorithm

**Comment by fverdugo** [comment]
@GeliezaK I am glad that the project gets started. Looking forward!

**Comment by GeliezaK** [comment]
@fverdugo @oriolcg @amartinhuertas 
I have a question about how to achieve 1D and 2D block partitioning. 
I would like to implement the 2D Jacobi method as a toy project. This is the code for partitioning the data into blocks of rows like this: 

<img src="https://github.com/fverdugo/PartitionedArrays.jl/assets/76211195/0359f4bc-37b8-463d-8142-a8f564a9b46c" width="100">

```julia
function jacobi_2d_par(n,niters,p)
    # Stip-wise block partition 
    ranks = DebugArray(LinearIndices((p,)))
    ghost = true
    row_partition = uniform_partition(ranks, n+2, ghost)
    
    IJV = map(row_partition) do row_indices
        I,J,V = Int[], Int[], Float64[]
        for global_row in local_to_global(row_indices)
            for col in 1:n+2
                push!(I, global_row)
                push!(J, col)
                if global_row in (1,n+2)
                    push!(V,1)
                elseif col in (1,n+2)
                    push!(V,1)
                else 
                    push!(V,0)
                end
            end
        end
        I,J,V
    end
    
    I, J, V = tuple_of_arrays(IJV)
    col_partition = row_partition
    A = psparse(I,J,V, row_partition, col_partition) |> fetch 

    # Jacobi update
end 
  ```

This code gives me the error "replace_ghost only makes sense for un-permuted local indices." Can you help me understand how to build this partition with ghost cells? 

I'm also interested in building a 2D block partion like this: 

<img src="https://github.com/fverdugo/PartitionedArrays.jl/assets/76211195/279a9ab8-d5e8-4c09-92da-a0414bda1d2e" width="100">

Thanks a lot!

**Comment by fverdugo** [comment]
Hi @GeliezaK

For the 2d jacobi (5-point stencil) you don't need a sparse matrix. Just two vectors as in the 1d case. Think of these 1d vectors as the 1d representation of dense matrices. Another way of implementing this is by explicitly using distributed dense matrices, but there are not yet implemented in PartitionedArrays: see issue  #97. See my comments there.

**Comment by amartinhuertas** [comment]
Hi @GeliezaK, 

let us talk tomorrow at the meeting about this.

**Comment by GeliezaK** [comment]
Meeting notes from 2024-06-06:

@oriolcg @fverdugo

Attendees: @GeliezaK @amartinhuertas 

Notes: 

- fixed point iterative linear solvers: update grid (Jacobi method) or update solution vector with residual (matrix operations) [(lecture slides 1,](https://comp.anu.edu.au/courses/comp4300/assets/lectures/synchComp1.pdf) [lecture slides 2)](https://comp.anu.edu.au/courses/comp4300/assets/lectures/synchComp2.pdf)
- partitioning of grid vs. systems matrix
- content of and differences between Project.toml and Manifest.toml
- resources for introduction to AMG: [An Introduction to AMG](https://www.osti.gov/biblio/897960), [A multigrid tutorial](https://www.math.hkust.edu.hk/~mamu/courses/531/tutorial_with_corrections.pdf) 

Action points: 

- [ ] read thesis/other AMG resources and gain understanding of algorithms

- [ ] remove Manifest.toml from pull request

- [ ] continue implementation of Jacobi method with different types of partitioning

- [ ] implement solution of 2d laplace equation to practice working with PSparse matrices
