### ISSUE TITLE
Reduction Operates Successfully in Debug Mode but Fails in MPI Mode

### ISSUE THREAD

**Issue by ZhangFengshun** [fverdugo/PartitionedArrays.jl#160]
Hi~, I try to run this code to test Allreduce functionality. It works in Debug mode but encounters failure when executed in MPI mode.

Code:
![image](https://github.com/user-attachments/assets/936f2455-1bc4-4c09-939a-dc331ce7f9fc)

Errors:
![image](https://github.com/user-attachments/assets/5327d8e5-c156-4d12-89d6-d94acf096ea0)

**Comment by fverdugo** [comment]
Hi @ZhangFengshun 

For now, you first need to reduce locally and then call reduction

```julia
tmp = map(reduce,a_snd)
reduction(+,tmp;init=0,destination=2)
```

**Comment by ZhangFengshun** [comment]
> Hi @ZhangFengshun
> 
> For now, you first need to reduce locally and then call reduction
> 
> ```julia
> tmp = map(reduce,a_snd)
> reduction(+,tmp;init=0,destination=2)
> ```

Thank you for your timely reply. PartitionedArrays is a very useful MPI tool in Julia.
