### ISSUE TITLE
discover_snd_parts warning

### ISSUE THREAD

**Issue by amartinhuertas** [fverdugo/PartitionedArrays.jl#41]
Hi @fverdugo, 

we know that the current implementation of `discover_snd_parts` is not scalable. However, the user might not know that. While we dont have an scalable implementation I would warn the user on screen with a message. Something like: 

"[PartitionedArrays.jl] Warning: Using a non-scalable implementation to discover reciprocal parts in sparse communication kernel among nearest neighbours. This might cause trouble when running the code at medium/large scales. You can avoid this using the Exchanger constructor with bla bla bla"

I guess that we can do it on the master task using the `@warn` macro right at the beginning of a call to `discover_parts_snd`. 

What do you think? Any other ideas while we do not have the scalable solution?

**Comment by fverdugo** [comment]
We can add this warning no problem. It would be useful to check that we always use the scalable versions (i.e. by running our CI always with error on warning)

**Comment by amartinhuertas** [comment]
> We can add this warning no problem. 

Done in PR https://github.com/fverdugo/PartitionedArrays.jl/pull/42

> It would be useful to check that we always use the scalable versions (i.e. by running our CI always with error on warning)

I think we cannot do that, right? I mean that we are willing to test the non-scalable version on CI as well.
