### ISSUE TITLE
Docs need some examples

### ISSUE THREAD

**Issue by termi-official** [fverdugo/PartitionedArrays.jl#75]
First and foremost, thanks for providing the package. It looks like it can be very useful for aiding in the field and solution management on a large battery of methods for PDE discretizations. However, I the package has quite a high barrier of entry, as no minimal examples are provided. I tried to reconstruct how to use the package from the linked Poisson example (i.e. PartitionedPoisson.jl) and GridapDistributed.jl, but made just minor progress over the last few days. 

Trying to construct some very minimalistic example with two processes (distributed discretization of a Poisson problem in 1d into 5 elements on 2 processes, where process 1 owns the first 3 dofs and process two the last 2) I ran into the issue that I have some trouble solving the problem with a cg.

For reproduction some code (don't mind the variable names, this is a quickly stripped down version of some other code)
```
using MPI, PartitionedArrays, SparseArrays, IterativeSolvers, LinearAlgebra
const PArrays = PartitionedArrays

# Get MPI information
MPI.Init()
comm    = MPI.COMM_WORLD
my_rank = MPI.Comm_rank(comm)
np      = MPI.Comm_size(comm)

# Partition matrix row by row
ngdofs = 5
if my_rank == 0
    neighbors = MPIData(Int32[2], comm, (np,))
    dof_partition = MPIData(PArrays.IndexSet(my_rank+1, [1,2,3], Int32[1,1,1]), comm, (np,))
    allcols = MPIData(PArrays.IndexSet(my_rank+1, [1,2,3,4], Int32[1,1,1,2]), comm, (np,))
else
    neighbors = MPIData(Int32[1], comm, (np,))
    dof_partition = MPIData(PArrays.IndexSet(my_rank+1, [3,4,5], Int32[1,2,2]), comm, (np,))
    allcols = MPIData(PArrays.IndexSet(my_rank+1, [3,4,5], Int32[1,2,2]), comm, (np,))
end
dof_exchanger = Exchanger(dof_partition,neighbors)
rows = PRange(ngdofs,dof_partition,dof_exchanger)
cols = PRange(ngdofs,allcols,Exchanger(allcols,neighbors))

# Fill COO triplets
if my_rank == 0
    I_ = MPIData([ 1, 1, 2, 2, 2, 3, 3, 3], comm, (np,))
    J_ = MPIData([ 1, 2, 1, 2, 3, 2, 3, 4], comm, (np,))
    V_ = MPIData(Float64[1, 0, 0,-2, 1, 1,-1, 0], comm, (np,))
else
    I_ = MPIData([ 1, 1, 2, 2, 2, 3, 3], comm, (np,))
    J_ = MPIData([ 1, 2, 1, 2, 3, 2, 3], comm, (np,))
    V_ = MPIData(Float64[-1, 1, 1,-2, 1, 1,-1], comm, (np,))
end

# Construct the actual sparse matrix
#
#    P1  P1  P1  P2  P2
# P1  1   0   0   0   0
# P1  0  -2   1   0   0   
# P1  0   1  -2   1   0
# P2  0   0   1  -2   1
# P2  0   0   0   1  -1
#
#               =
#
#    P1  P1  P1  P2  P2
# P1  1   0   0   0   0
# P1  0  -2   1   0   0
# P1  0   1  -1   0   0
# P2  x   x   x   x   x
# P2  x   x   x   x   x
#
#              + 
# 
#    P1  P1  P1  P2  P2
# P1  x   x   x   x   x
# P1  x   x   x   x   x   
# P1  0   0  -1   1   0
# P2  0   0   1  -2   1
# P2  0   0   0   1  -1

K = PArrays.PSparseMatrix(I_, J_, V_, rows, cols, ids=:local)

# Trigger sync
PArrays.assemble!(K)

# Construct a constant vector 
x = PVector{Float64}(undef,K.cols)
fill!(x, 1.0)
assemble!(x)

# SPMV works
y = K*x

# Provided direct solver works
x_solved = K\y
r = K*x_solved - y
@assert norm(x_solved - x) < 1e-8

# Solve problem with cg seem to work now
x_solved = IterativeSolvers.cg(K,y)
r = K*x_solved - y
@assert norm(x_solved - x) < 1e-8
```

the last norm fails. ~~My first guess is that the cg fails due to improper synchronization of the SPMV results.~~ Edit: cg needs a symmetric matrix. :) However, with the symmetric matrix now the cg works ~~but the direct solver fails.~~. Also works when typing the values.

+- constructing the MPIData objects by hand, is this how to construct the PSparseMatrix, PRange and Exchanger?

Also, are there some debug methods aiding to inspect the resulting distributed matrix?

**Comment by fverdugo** [comment]
BTW with the sequential backend you can run code incrementally/interactivelly in the Julia REPL (i.e. without writing it in a single main function). Just create the `parts` object with `parts=get_part_ids(SequentialBackend(),np)`.

**Comment by termi-official** [comment]
Thanks for the elaborate response @fverdugo . Running your improved version of the code I realized that I seem to have some total misunderstanding with the *Data objects. This design is really cool and helpful! Happy to make a PR add some docs once I figure out more details on the package.

> > Also, are there some debug methods aiding to inspect the resulting distributed matrix?
> 
> sure
> 
> `display(parts)`, `display(neighbors)`, `display(rows.partition)`, `display(K.values)` etc

This is what I do currently, but I was thinking about some convenience methods to e.g. print out the full matrix (to stdout or a file) or just the purely local view for debugging purposes (in contrast to manually picking the data structures apart). From your response I guess from the answer that such methods are stuff for future PRs.
