### ISSUE TITLE
Compatibility broken for PartitionedArrays 0.2.12

### ISSUE THREAD

**Issue by JordiManyer** [fverdugo/PartitionedArrays.jl#89]
I've noticed that `MPI.jl` 0.20 is now supported, which is good. However, this means we cannot have compatibility with older versions of `MPI.jl`, since the `MPI.API` module was introduced in 0.20 and is explicitly used in some `PartitionedArrays` functions, for instance `PartitionedArrays.jl/MPIBackend.jl/_get_part_ids_body(...)`. 

I noticed this while trying to use the new version of `PartitionedArrays.jl` in `GridapDistributed.jl` and `GridapP4est.jl`. 

I then believe the compat line in `Project.toml` should read
```
MPI = "0.20"
```
Let me know what you think.

**Comment by JordiManyer** [comment]
or a little more context, this is what happens when you try to use `PartitionedArrays.jl` v0.2.12 with `MPI.jl` v0.19.2

```
┌ Error: 
│   exception =
│    UndefVarError: API not defined
│    Stacktrace:
│     [1] _get_part_ids_body(root_comm::MPI.Comm, rank::Int64, size::Int64, need::Int64, nparts::Int64)
│       @ PartitionedArrays ~/.julia/packages/PartitionedArrays/dwJNy/src/MPIBackend.jl:72
│     [2] get_part_ids(b::PartitionedArrays.MPIBackend, nparts::Int64)
│       @ PartitionedArrays ~/.julia/packages/PartitionedArrays/dwJNy/src/MPIBackend.jl:53
│     [3] with_backend(::typeof(Main.OctreeDistributedDiscreteModelsTests.run), ::PartitionedArrays.MPIBackend, ::Int64, ::Tuple{Int64, Int64}, ::Vararg{Any}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
│       @ PartitionedArrays ~/.julia/packages/PartitionedArrays/dwJNy/src/MPIBackend.jl:91
│     [4] with_backend(::Function, ::PartitionedArrays.MPIBackend, ::Int64, ::Tuple{Int64, Int64}, ::Vararg{Any})
│       @ PartitionedArrays ~/.julia/packages/PartitionedArrays/dwJNy/src/MPIBackend.jl:82
│     [5] top-level scope
│       @ ~/Documents/GridapP4est.jl/test/OctreeDistributedDiscreteModelsTests.jl:78
│     [6] include(mod::Module, _path::String)
│       @ Base ./Base.jl:419
│     [7] exec_options(opts::Base.JLOptions)
│       @ Base ./client.jl:303
│     [8] _start()
│       @ Base ./client.jl:522
└ @ PartitionedArrays ~/.julia/packages/PartitionedArrays/dwJNy/src/MPIBackend.jl:94
```

**Comment by JordiManyer** [comment]
@amartinhuertas @fverdugo

**Comment by fverdugo** [comment]
I tried to make the code work with MPI.jl 0.20 and pre 0.20 by adding these kind of if statements like here : https://github.com/fverdugo/PartitionedArrays.jl/blob/1be6cde8c4863f6f084ce55f9c546ce9b81c3928/src/MPIBackend.jl#L328


Can you try to do the same in the parts failing?

**Comment by fverdugo** [comment]
@amartinhuertas can you take a look at this?

**Comment by amartinhuertas** [comment]
Fixed. See PR #90
